// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: dispatch.proto

package dispatchpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DispatchService_Dispatch_FullMethodName       = "/dispatch.v1.DispatchService/Dispatch"
	DispatchService_RespondToOffer_FullMethodName = "/dispatch.v1.DispatchService/RespondToOffer"
)

// DispatchServiceClient is the client API for DispatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DispatchService is exposed by every disco node. A node that receives a
// request for a cell it does not own forwards it here, to the node that
// does, rather than answering for a cell it isn't authoritative over.
type DispatchServiceClient interface {
	// Dispatch runs the full match-and-offer pipeline for a ride request
	// whose origin cell this node owns.
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	// RespondToOffer delivers a driver's accept/decline for whatever trip is
	// currently offered to them. A driver's client only ever knows its own
	// driver ID, not which node is running that trip's dispatch loop or even
	// the trip ID itself - the receiving node looks both up via Redis
	// (OfferStore.CurrentOfferFor) and forwards to the owning node exactly
	// like Dispatch does, so a driver can call any node.
	RespondToOffer(ctx context.Context, in *RespondToOfferRequest, opts ...grpc.CallOption) (*RespondToOfferResponse, error)
}

type dispatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchServiceClient(cc grpc.ClientConnInterface) DispatchServiceClient {
	return &dispatchServiceClient{cc}
}

func (c *dispatchServiceClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, DispatchService_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) RespondToOffer(ctx context.Context, in *RespondToOfferRequest, opts ...grpc.CallOption) (*RespondToOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondToOfferResponse)
	err := c.cc.Invoke(ctx, DispatchService_RespondToOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchServiceServer is the server API for DispatchService service.
// All implementations must embed UnimplementedDispatchServiceServer
// for forward compatibility.
//
// DispatchService is exposed by every disco node. A node that receives a
// request for a cell it does not own forwards it here, to the node that
// does, rather than answering for a cell it isn't authoritative over.
type DispatchServiceServer interface {
	// Dispatch runs the full match-and-offer pipeline for a ride request
	// whose origin cell this node owns.
	Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error)
	// RespondToOffer delivers a driver's accept/decline for whatever trip is
	// currently offered to them. A driver's client only ever knows its own
	// driver ID, not which node is running that trip's dispatch loop or even
	// the trip ID itself - the receiving node looks both up via Redis
	// (OfferStore.CurrentOfferFor) and forwards to the owning node exactly
	// like Dispatch does, so a driver can call any node.
	RespondToOffer(context.Context, *RespondToOfferRequest) (*RespondToOfferResponse, error)
	mustEmbedUnimplementedDispatchServiceServer()
}

// UnimplementedDispatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDispatchServiceServer struct{}

func (UnimplementedDispatchServiceServer) Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedDispatchServiceServer) RespondToOffer(context.Context, *RespondToOfferRequest) (*RespondToOfferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToOffer not implemented")
}
func (UnimplementedDispatchServiceServer) mustEmbedUnimplementedDispatchServiceServer() {}
func (UnimplementedDispatchServiceServer) testEmbeddedByValue()                         {}

// UnsafeDispatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchServiceServer will
// result in compilation errors.
type UnsafeDispatchServiceServer interface {
	mustEmbedUnimplementedDispatchServiceServer()
}

func RegisterDispatchServiceServer(s grpc.ServiceRegistrar, srv DispatchServiceServer) {
	// If the following call panics, it indicates UnimplementedDispatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DispatchService_ServiceDesc, srv)
}

func _DispatchService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_RespondToOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondToOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).RespondToOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_RespondToOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).RespondToOffer(ctx, req.(*RespondToOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DispatchService_ServiceDesc is the grpc.ServiceDesc for DispatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DispatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dispatch.v1.DispatchService",
	HandlerType: (*DispatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _DispatchService_Dispatch_Handler,
		},
		{
			MethodName: "RespondToOffer",
			Handler:    _DispatchService_RespondToOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dispatch.proto",
}
